name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '>=16.0.0'
      - name: Install dependencies
        run: yarn
      - name: Build OpenTicket
        run: yarn build
      - name: Remove dist
        run: yarn clean
